config/routes.rb
Rails.application.routes.draw do
  resources :tracks
  resources :welcome, only: [:index]
  resources :favorites, only: [:index, :create, :destroy]
  post 'tracks/:id', to: 'tracks#show'
  match 'search', to: 'tracks#search', via: [:get, :post]
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  root to: 'tracks#index'
end

app/controllers/tracks_controller.rb
require 'json'

class TracksController < ApplicationController
  def index
    @consumer = OAuth::Consumer.new(ENV['OMNIAUTH_PROVIDER_KEY'], ENV['OMNIAUTH_PROVIDER_SECRET'], {:site=>ENV['OAUTH_CONSUMER_SITE']})
    @accesstoken = OAuth::AccessToken.new(@consumer, session[:token], session[:secret])
    @tracks = JSON.parse(@accesstoken.get('https://oauth-api.beatport.com/catalog/3/most-popular').body)
    @results = Kaminari.paginate_array(@tracks["results"].to_a).page(params[:page]).per(10)
    redirect_to :welcome_index unless user_signed_in? 
  end

  def search
    @consumer = OAuth::Consumer.new(ENV['OMNIAUTH_PROVIDER_KEY'], ENV['OMNIAUTH_PROVIDER_SECRET'], {:site=>ENV['OAUTH_CONSUMER_SITE']})
    @accesstoken = OAuth::AccessToken.new(@consumer, session[:token], session[:secret])
    @tracks = JSON.parse(@accesstoken.get("https://oauth-api.beatport.com/catalog/3/search/?query=#{URI.encode(params[:query])}&perPage=150").body)
    @results = Kaminari.paginate_array(@tracks["results"].to_a.delete_if {|key, value| key["type"] !="track" }).page(params[:page]).per(15)
    render 'index'
  end

  def show
    @consumer = OAuth::Consumer.new(ENV['OMNIAUTH_PROVIDER_KEY'], ENV['OMNIAUTH_PROVIDER_SECRET'], {:site=>ENV['OAUTH_CONSUMER_SITE']})
    @accesstoken = OAuth::AccessToken.new(@consumer, session[:token], session[:secret])
    @similar_tracks = JSON.parse(@accesstoken.get("https://oauth-api.beatport.com/catalog/3/tracks/similar?id=#{URI.encode(params[:id])}&perPage=20").body)
    @affinite_results = Kaminari.paginate_array(@similar_tracks["results"].to_a.delete_if {|key, value| key["type"] !="track" }).page(params[:page]).per(15)
    @track_key = params[:key]
  end

  private
  def search_params
    params.require(:search).permit(:query)
  end
end

app/helpers/tracks_helper.rb
require 'htmlentities'

module TracksHelper
  def decode_entities(string)
    HTMLEntities.new.decode(string)
  end

  def collect_artists(hash)
    hash.map { |a| a["name"] if a["type"] == "artist"}.compact * ", " unless hash.nil?
  end

  def encode_key(string)
    Monad.by_name(decode_entities(string))
  end

  def affinity?(selected_monad, comparison_monad)
    AffinityFinder.match?(selected_monad, comparison_monad)
  end

  def favorited(string)
    if current_user.favorites.exists?(title: string)
      true
    else
      false
    end
  end
end

app/views/tracks/_affinite_result.html.haml
- if affinity?(encode_key(affinite_result["key"]["shortName"]), encode_key(@track_key))
  %li.result.pam.mbl.g-b
    .mlxs.artcover
      = image_tag affinite_result["images"]["large"]["url"], :height => "130", :width => "130"
    .key.g-b.g-b--l--1of12= decode_entities(affinite_result["key"]["shortName"])
    .bpm.g-b.g-b--l--1of12= affinite_result["bpm"]
    .mts.g-b.g-b--l--7of12
      = collect_artists(affinite_result["artists"])
    .mts.g-b.g-b--l--7of12= affinite_result["title"]
    .player.mtm.g-b
      = audio_tag("http://geo-samples.beatport.com/lofi/#{affinite_result["id"]}.LOFI.mp3", controls: true, preload: false)
      = button_to('', track_path(id: affinite_result["id"], key: decode_entities(affinite_result["key"]["shortName"])))
      = favorited(affinite_result["title"]) ? link_to( icon('frown-o'), Favorite.find_by(title: affinite_result["title"]), remote: true, :method => :delete, class: 'unfavorited') : link_to(icon('smile-o'), favorites_path(favorite: {image_url: affinite_result["images"]["large"]["url"], key: decode_entities(affinite_result["key"]["shortName"]), bpm: affinite_result["bpm"], artist: collect_artists(affinite_result["artists"]), title: affinite_result["title"], track_id: affinite_result["id"]}), remote: true, :method => :post, class: 'favorited')
      = !favorited(affinite_result["title"]) ? link_to( icon('frown-o'), Favorite.find_by(title: affinite_result["title"]), remote: true, :method => :delete, class: 'unfavorited', style: 'display: none') : link_to(icon('smile-o'), favorites_path(favorite: {image_url: affinite_result["images"]["large"]["url"], key: decode_entities(affinite_result["key"]["shortName"]), bpm: affinite_result["bpm"], artist: collect_artists(affinite_result["artists"]), title: affinite_result["title"], track_id: affinite_result["id"]}), remote: true, :method => :post, class: 'favorited', style: 'display: none')

app/views/tracks/_result.html.haml
%li.result.pam.mbl.g-b{:id => result["id"]}
  .mlxs.artcover
    = image_tag result["images"]["large"]["url"], :height => "130", :width => "130"
  .key.g-b.g-b--l--1of12= decode_entities(result["key"]["shortName"]) unless result["key"].nil?
  .bpm.g-b.g-b--l--1of12= result["bpm"]
  .artists.mts.g-b.g-b--l--7of12
    = collect_artists(result["artists"])
  .title.mts.g-b.g-b--l--7of12= result["title"]
  .player.mtm.g-b
    = audio_tag("http://geo-samples.beatport.com/lofi/#{result["id"]}.LOFI.mp3", controls: true, preload: false)
    = button_to('', track_path(id: result["id"], key: decode_entities(result["key"]["shortName"]))) unless result["key"].nil?
    = favorited(result["title"]) ? link_to( icon('frown-o'), Favorite.find_by(title: result["title"]), remote: true, :method => :delete, class: 'unfavorited') : link_to(icon('smile-o'), favorites_path(favorite: {image_url: result["images"]["large"]["url"], key: decode_entities(result["key"]["shortName"]), bpm: result["bpm"], artist: collect_artists(result["artists"]), title: result["title"], track_id: result["id"]}), remote: true, :method => :post, class: 'favorited')
    = !favorited(result["title"]) ? link_to( icon('frown-o'), Favorite.find_by(title: result["title"]), remote: true, :method => :delete, class: 'unfavorited', style: 'display: none') : link_to(icon('smile-o'), favorites_path(favorite: {image_url: result["images"]["large"]["url"], key: decode_entities(result["key"]["shortName"]), bpm: result["bpm"], artist: collect_artists(result["artists"]), title: result["title"], track_id: result["id"]}), remote: true, :method => :post, class: 'favorited', style: 'display: none')

app/views/tracks/_results.html.haml
%ul.result
  %li.result.pam.mbl.g-b{:id => result["id"]}
    .mlxs.artcover
      = image_tag result["images"]["large"]["url"], :height => "130", :width => "130"
    .key.g-b.g-b--l--1of12= decode_entities(result["key"]["shortName"]) unless result["key"].nil?
    .bpm.g-b.g-b--l--1of12= result["bpm"]
    .artists.mts.g-b.g-b--l--7of12
      = collect_artists(result["artists"])
    .title.mts.g-b.g-b--l--7of12= result["title"]
    .player.mtm.g-b
      = audio_tag("http://geo-samples.beatport.com/lofi/#{result["id"]}.LOFI.mp3", controls: true, preload: false)
      = button_to('', track_path(id: result["id"], key: decode_entities(result["key"]["shortName"]))) unless result["key"].nil?
      = favorited(result["title"]) ? link_to( icon('frown-o'), Favorite.find_by(title: result["title"]), remote: true, :method => :delete, class: 'unfavorited') : link_to(icon('smile-o'), favorites_path(favorite: {image_url: result["images"]["large"]["url"], key: decode_entities(result["key"]["shortName"]), bpm: result["bpm"], artist: collect_artists(result["artists"]), title: result["title"], track_id: result["id"]}), remote: true, :method => :post, class: 'favorited')
      = !favorited(result["title"]) ? link_to( icon('frown-o'), Favorite.find_by(title: result["title"]), remote: true, :method => :delete, class: 'unfavorited', style: 'display: none') : link_to(icon('smile-o'), favorites_path(favorite: {image_url: result["images"]["large"]["url"], key: decode_entities(result["key"]["shortName"]), bpm: result["bpm"], artist: collect_artists(result["artists"]), title: result["title"], track_id: result["id"]}), remote: true, :method => :post, class: 'favorited', style: 'display: none')

app/views/tracks/index.html.haml
= render 'layouts/shared/sidebar'

%div.row.row--c
  %div#results.g-b.g-b--center
    %ul.page
      = render partial: 'result', collection: @results
    = paginate @results

app/views/tracks/index.js.erb
$('ul.page').append('<%= escape_javascript render(:partial => 'result', :collection => @results) %>');

<% if @results.current_page < @results.num_pages %>
  $('.pagination').replaceWith('<%= j paginate(@results) %>');
  console.log('next');
<% else %>
  $('.pagination').remove();
<% end %>
<% sleep 1 %>

app/views/tracks/show.html.haml
= render 'layouts/shared/sidebar'

%div.row.row--c
  %div#results.g-b.g-b--l--11of12.g-b--center
    %ul.page
      = render partial: 'affinite_result', collection: @affinite_results
    = paginate @affinite_results

app/views/tracks/show.js.erb
$('ul.page').append('<%= escape_javascript render(:partial => 'affinite_result', :collection => @affinite_results) %>');

<% if @affinite_results.current_page < @affinite_results.num_pages %>
  $('.pagination').replaceWith('<%= j paginate(@affinite_results) %>');
  console.log('next');
<% else %>
  $('.pagination').remove();
<% end %>
<% sleep 1 %>