config/routes.rb
Rails.application.routes.draw do
  resources :tracks
  resources :welcome, only: [:index]
  resources :favorites, only: [:index, :create, :destroy]
  post 'tracks/:id', to: 'tracks#show'
  match 'search', to: 'tracks#search', via: [:get, :post]
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  root to: 'tracks#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    render layout: false 
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.haml
!!! 5
%html{ lang: 'en' }
%head
  %title= "Avalon Simple Search"
  = yield(:meta_content)
  %meta{ :name => 'viewport', :content => 'width=device-width, initial-scale=1' }
  = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Merriweather:400,300,700,400italic'
  = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Rajdhani:300,400,500,600,700'
  = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700,300italic,400italic,500italic,700italic'
  = stylesheet_link_tag 'http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css'
  = stylesheet_link_tag 'application'
  = csrf_meta_tags
%body
  %div.splash
  %div
    %div
      %h1.splash Avalon

    %div.desc
      %p
        = "Discover new music harmonically."

    %div.signin
      = link_to 'Sign in >>', signin_path, :class => 'splash'
      .register= link_to 'Not Registered?', 'https://pro.beatport.com/account/signup/', :class => 'splash'
  = javascript_include_tag 'application'